# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tommy/Workspace/Xion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tommy/Workspace/Xion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tommy/Workspace/Xion/CMakeFiles /home/tommy/Workspace/Xion/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tommy/Workspace/Xion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xion

# Build rule for target.
xion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xion
.PHONY : xion

# fast build rule for target.
xion/fast:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/build
.PHONY : xion/fast

#=============================================================================
# Target rules for targets named xionTest

# Build rule for target.
xionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xionTest
.PHONY : xionTest

# fast build rule for target.
xionTest/fast:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/build
.PHONY : xionTest/fast

#=============================================================================
# Target rules for targets named xionTesting

# Build rule for target.
xionTesting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xionTesting
.PHONY : xionTesting

# fast build rule for target.
xionTesting/fast:
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/build
.PHONY : xionTesting/fast

modules/dataset/dataset.o: modules/dataset/dataset.c.o
.PHONY : modules/dataset/dataset.o

# target to build an object file
modules/dataset/dataset.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/dataset.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/dataset.c.o
.PHONY : modules/dataset/dataset.c.o

modules/dataset/dataset.i: modules/dataset/dataset.c.i
.PHONY : modules/dataset/dataset.i

# target to preprocess a source file
modules/dataset/dataset.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/dataset.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/dataset.c.i
.PHONY : modules/dataset/dataset.c.i

modules/dataset/dataset.s: modules/dataset/dataset.c.s
.PHONY : modules/dataset/dataset.s

# target to generate assembly for a file
modules/dataset/dataset.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/dataset.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/dataset.c.s
.PHONY : modules/dataset/dataset.c.s

modules/dataset/datasetController.o: modules/dataset/datasetController.c.o
.PHONY : modules/dataset/datasetController.o

# target to build an object file
modules/dataset/datasetController.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/datasetController.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/datasetController.c.o
.PHONY : modules/dataset/datasetController.c.o

modules/dataset/datasetController.i: modules/dataset/datasetController.c.i
.PHONY : modules/dataset/datasetController.i

# target to preprocess a source file
modules/dataset/datasetController.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/datasetController.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/datasetController.c.i
.PHONY : modules/dataset/datasetController.c.i

modules/dataset/datasetController.s: modules/dataset/datasetController.c.s
.PHONY : modules/dataset/datasetController.s

# target to generate assembly for a file
modules/dataset/datasetController.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/datasetController.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/datasetController.c.s
.PHONY : modules/dataset/datasetController.c.s

modules/dataset/datasetValidator.o: modules/dataset/datasetValidator.c.o
.PHONY : modules/dataset/datasetValidator.o

# target to build an object file
modules/dataset/datasetValidator.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/datasetValidator.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/datasetValidator.c.o
.PHONY : modules/dataset/datasetValidator.c.o

modules/dataset/datasetValidator.i: modules/dataset/datasetValidator.c.i
.PHONY : modules/dataset/datasetValidator.i

# target to preprocess a source file
modules/dataset/datasetValidator.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/datasetValidator.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/datasetValidator.c.i
.PHONY : modules/dataset/datasetValidator.c.i

modules/dataset/datasetValidator.s: modules/dataset/datasetValidator.c.s
.PHONY : modules/dataset/datasetValidator.s

# target to generate assembly for a file
modules/dataset/datasetValidator.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/datasetValidator.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/datasetValidator.c.s
.PHONY : modules/dataset/datasetValidator.c.s

modules/dataset/serializer.o: modules/dataset/serializer.c.o
.PHONY : modules/dataset/serializer.o

# target to build an object file
modules/dataset/serializer.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/serializer.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/serializer.c.o
.PHONY : modules/dataset/serializer.c.o

modules/dataset/serializer.i: modules/dataset/serializer.c.i
.PHONY : modules/dataset/serializer.i

# target to preprocess a source file
modules/dataset/serializer.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/serializer.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/serializer.c.i
.PHONY : modules/dataset/serializer.c.i

modules/dataset/serializer.s: modules/dataset/serializer.c.s
.PHONY : modules/dataset/serializer.s

# target to generate assembly for a file
modules/dataset/serializer.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/dataset/serializer.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/dataset/serializer.c.s
.PHONY : modules/dataset/serializer.c.s

modules/features/haarFeature.o: modules/features/haarFeature.c.o
.PHONY : modules/features/haarFeature.o

# target to build an object file
modules/features/haarFeature.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/features/haarFeature.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/features/haarFeature.c.o
.PHONY : modules/features/haarFeature.c.o

modules/features/haarFeature.i: modules/features/haarFeature.c.i
.PHONY : modules/features/haarFeature.i

# target to preprocess a source file
modules/features/haarFeature.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/features/haarFeature.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/features/haarFeature.c.i
.PHONY : modules/features/haarFeature.c.i

modules/features/haarFeature.s: modules/features/haarFeature.c.s
.PHONY : modules/features/haarFeature.s

# target to generate assembly for a file
modules/features/haarFeature.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/features/haarFeature.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/features/haarFeature.c.s
.PHONY : modules/features/haarFeature.c.s

modules/features/haarFeatureGenerator.o: modules/features/haarFeatureGenerator.c.o
.PHONY : modules/features/haarFeatureGenerator.o

# target to build an object file
modules/features/haarFeatureGenerator.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/features/haarFeatureGenerator.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/features/haarFeatureGenerator.c.o
.PHONY : modules/features/haarFeatureGenerator.c.o

modules/features/haarFeatureGenerator.i: modules/features/haarFeatureGenerator.c.i
.PHONY : modules/features/haarFeatureGenerator.i

# target to preprocess a source file
modules/features/haarFeatureGenerator.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/features/haarFeatureGenerator.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/features/haarFeatureGenerator.c.i
.PHONY : modules/features/haarFeatureGenerator.c.i

modules/features/haarFeatureGenerator.s: modules/features/haarFeatureGenerator.c.s
.PHONY : modules/features/haarFeatureGenerator.s

# target to generate assembly for a file
modules/features/haarFeatureGenerator.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/features/haarFeatureGenerator.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/features/haarFeatureGenerator.c.s
.PHONY : modules/features/haarFeatureGenerator.c.s

modules/frameworks/adaBoost.o: modules/frameworks/adaBoost.c.o
.PHONY : modules/frameworks/adaBoost.o

# target to build an object file
modules/frameworks/adaBoost.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/adaBoost.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/adaBoost.c.o
.PHONY : modules/frameworks/adaBoost.c.o

modules/frameworks/adaBoost.i: modules/frameworks/adaBoost.c.i
.PHONY : modules/frameworks/adaBoost.i

# target to preprocess a source file
modules/frameworks/adaBoost.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/adaBoost.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/adaBoost.c.i
.PHONY : modules/frameworks/adaBoost.c.i

modules/frameworks/adaBoost.s: modules/frameworks/adaBoost.c.s
.PHONY : modules/frameworks/adaBoost.s

# target to generate assembly for a file
modules/frameworks/adaBoost.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/adaBoost.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/adaBoost.c.s
.PHONY : modules/frameworks/adaBoost.c.s

modules/frameworks/attentionalCascade.o: modules/frameworks/attentionalCascade.c.o
.PHONY : modules/frameworks/attentionalCascade.o

# target to build an object file
modules/frameworks/attentionalCascade.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/attentionalCascade.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/attentionalCascade.c.o
.PHONY : modules/frameworks/attentionalCascade.c.o

modules/frameworks/attentionalCascade.i: modules/frameworks/attentionalCascade.c.i
.PHONY : modules/frameworks/attentionalCascade.i

# target to preprocess a source file
modules/frameworks/attentionalCascade.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/attentionalCascade.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/attentionalCascade.c.i
.PHONY : modules/frameworks/attentionalCascade.c.i

modules/frameworks/attentionalCascade.s: modules/frameworks/attentionalCascade.c.s
.PHONY : modules/frameworks/attentionalCascade.s

# target to generate assembly for a file
modules/frameworks/attentionalCascade.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/attentionalCascade.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/attentionalCascade.c.s
.PHONY : modules/frameworks/attentionalCascade.c.s

modules/frameworks/main.o: modules/frameworks/main.c.o
.PHONY : modules/frameworks/main.o

# target to build an object file
modules/frameworks/main.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/main.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/main.c.o
.PHONY : modules/frameworks/main.c.o

modules/frameworks/main.i: modules/frameworks/main.c.i
.PHONY : modules/frameworks/main.i

# target to preprocess a source file
modules/frameworks/main.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/main.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/main.c.i
.PHONY : modules/frameworks/main.c.i

modules/frameworks/main.s: modules/frameworks/main.c.s
.PHONY : modules/frameworks/main.s

# target to generate assembly for a file
modules/frameworks/main.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/frameworks/main.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/frameworks/main.c.s
.PHONY : modules/frameworks/main.c.s

modules/preprocessing/integralImage.o: modules/preprocessing/integralImage.c.o
.PHONY : modules/preprocessing/integralImage.o

# target to build an object file
modules/preprocessing/integralImage.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/preprocessing/integralImage.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/preprocessing/integralImage.c.o
.PHONY : modules/preprocessing/integralImage.c.o

modules/preprocessing/integralImage.i: modules/preprocessing/integralImage.c.i
.PHONY : modules/preprocessing/integralImage.i

# target to preprocess a source file
modules/preprocessing/integralImage.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/preprocessing/integralImage.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/preprocessing/integralImage.c.i
.PHONY : modules/preprocessing/integralImage.c.i

modules/preprocessing/integralImage.s: modules/preprocessing/integralImage.c.s
.PHONY : modules/preprocessing/integralImage.s

# target to generate assembly for a file
modules/preprocessing/integralImage.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/preprocessing/integralImage.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/preprocessing/integralImage.c.s
.PHONY : modules/preprocessing/integralImage.c.s

modules/preprocessing/normalization.o: modules/preprocessing/normalization.c.o
.PHONY : modules/preprocessing/normalization.o

# target to build an object file
modules/preprocessing/normalization.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/preprocessing/normalization.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/preprocessing/normalization.c.o
.PHONY : modules/preprocessing/normalization.c.o

modules/preprocessing/normalization.i: modules/preprocessing/normalization.c.i
.PHONY : modules/preprocessing/normalization.i

# target to preprocess a source file
modules/preprocessing/normalization.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/preprocessing/normalization.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/preprocessing/normalization.c.i
.PHONY : modules/preprocessing/normalization.c.i

modules/preprocessing/normalization.s: modules/preprocessing/normalization.c.s
.PHONY : modules/preprocessing/normalization.s

# target to generate assembly for a file
modules/preprocessing/normalization.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/preprocessing/normalization.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/preprocessing/normalization.c.s
.PHONY : modules/preprocessing/normalization.c.s

modules/reporting/timeEval.o: modules/reporting/timeEval.c.o
.PHONY : modules/reporting/timeEval.o

# target to build an object file
modules/reporting/timeEval.c.o:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/reporting/timeEval.c.o
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/reporting/timeEval.c.o
.PHONY : modules/reporting/timeEval.c.o

modules/reporting/timeEval.i: modules/reporting/timeEval.c.i
.PHONY : modules/reporting/timeEval.i

# target to preprocess a source file
modules/reporting/timeEval.c.i:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/reporting/timeEval.c.i
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/reporting/timeEval.c.i
.PHONY : modules/reporting/timeEval.c.i

modules/reporting/timeEval.s: modules/reporting/timeEval.c.s
.PHONY : modules/reporting/timeEval.s

# target to generate assembly for a file
modules/reporting/timeEval.c.s:
	$(MAKE) -f CMakeFiles/xion.dir/build.make CMakeFiles/xion.dir/modules/reporting/timeEval.c.s
	$(MAKE) -f CMakeFiles/xionTesting.dir/build.make CMakeFiles/xionTesting.dir/modules/reporting/timeEval.c.s
.PHONY : modules/reporting/timeEval.c.s

test/datasetControllerTest.o: test/datasetControllerTest.c.o
.PHONY : test/datasetControllerTest.o

# target to build an object file
test/datasetControllerTest.c.o:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetControllerTest.c.o
.PHONY : test/datasetControllerTest.c.o

test/datasetControllerTest.i: test/datasetControllerTest.c.i
.PHONY : test/datasetControllerTest.i

# target to preprocess a source file
test/datasetControllerTest.c.i:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetControllerTest.c.i
.PHONY : test/datasetControllerTest.c.i

test/datasetControllerTest.s: test/datasetControllerTest.c.s
.PHONY : test/datasetControllerTest.s

# target to generate assembly for a file
test/datasetControllerTest.c.s:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetControllerTest.c.s
.PHONY : test/datasetControllerTest.c.s

test/datasetTest.o: test/datasetTest.c.o
.PHONY : test/datasetTest.o

# target to build an object file
test/datasetTest.c.o:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetTest.c.o
.PHONY : test/datasetTest.c.o

test/datasetTest.i: test/datasetTest.c.i
.PHONY : test/datasetTest.i

# target to preprocess a source file
test/datasetTest.c.i:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetTest.c.i
.PHONY : test/datasetTest.c.i

test/datasetTest.s: test/datasetTest.c.s
.PHONY : test/datasetTest.s

# target to generate assembly for a file
test/datasetTest.c.s:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetTest.c.s
.PHONY : test/datasetTest.c.s

test/datasetValidatorTest.o: test/datasetValidatorTest.c.o
.PHONY : test/datasetValidatorTest.o

# target to build an object file
test/datasetValidatorTest.c.o:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetValidatorTest.c.o
.PHONY : test/datasetValidatorTest.c.o

test/datasetValidatorTest.i: test/datasetValidatorTest.c.i
.PHONY : test/datasetValidatorTest.i

# target to preprocess a source file
test/datasetValidatorTest.c.i:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetValidatorTest.c.i
.PHONY : test/datasetValidatorTest.c.i

test/datasetValidatorTest.s: test/datasetValidatorTest.c.s
.PHONY : test/datasetValidatorTest.s

# target to generate assembly for a file
test/datasetValidatorTest.c.s:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/datasetValidatorTest.c.s
.PHONY : test/datasetValidatorTest.c.s

test/integralImageTest.o: test/integralImageTest.c.o
.PHONY : test/integralImageTest.o

# target to build an object file
test/integralImageTest.c.o:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/integralImageTest.c.o
.PHONY : test/integralImageTest.c.o

test/integralImageTest.i: test/integralImageTest.c.i
.PHONY : test/integralImageTest.i

# target to preprocess a source file
test/integralImageTest.c.i:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/integralImageTest.c.i
.PHONY : test/integralImageTest.c.i

test/integralImageTest.s: test/integralImageTest.c.s
.PHONY : test/integralImageTest.s

# target to generate assembly for a file
test/integralImageTest.c.s:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/integralImageTest.c.s
.PHONY : test/integralImageTest.c.s

test/main.o: test/main.c.o
.PHONY : test/main.o

# target to build an object file
test/main.c.o:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/main.c.o
.PHONY : test/main.c.o

test/main.i: test/main.c.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.c.i:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/main.c.i
.PHONY : test/main.c.i

test/main.s: test/main.c.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.c.s:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/main.c.s
.PHONY : test/main.c.s

test/preprocessingTest.o: test/preprocessingTest.c.o
.PHONY : test/preprocessingTest.o

# target to build an object file
test/preprocessingTest.c.o:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/preprocessingTest.c.o
.PHONY : test/preprocessingTest.c.o

test/preprocessingTest.i: test/preprocessingTest.c.i
.PHONY : test/preprocessingTest.i

# target to preprocess a source file
test/preprocessingTest.c.i:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/preprocessingTest.c.i
.PHONY : test/preprocessingTest.c.i

test/preprocessingTest.s: test/preprocessingTest.c.s
.PHONY : test/preprocessingTest.s

# target to generate assembly for a file
test/preprocessingTest.c.s:
	$(MAKE) -f CMakeFiles/xionTest.dir/build.make CMakeFiles/xionTest.dir/test/preprocessingTest.c.s
.PHONY : test/preprocessingTest.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... xion"
	@echo "... xionTest"
	@echo "... xionTesting"
	@echo "... modules/dataset/dataset.o"
	@echo "... modules/dataset/dataset.i"
	@echo "... modules/dataset/dataset.s"
	@echo "... modules/dataset/datasetController.o"
	@echo "... modules/dataset/datasetController.i"
	@echo "... modules/dataset/datasetController.s"
	@echo "... modules/dataset/datasetValidator.o"
	@echo "... modules/dataset/datasetValidator.i"
	@echo "... modules/dataset/datasetValidator.s"
	@echo "... modules/dataset/serializer.o"
	@echo "... modules/dataset/serializer.i"
	@echo "... modules/dataset/serializer.s"
	@echo "... modules/features/haarFeature.o"
	@echo "... modules/features/haarFeature.i"
	@echo "... modules/features/haarFeature.s"
	@echo "... modules/features/haarFeatureGenerator.o"
	@echo "... modules/features/haarFeatureGenerator.i"
	@echo "... modules/features/haarFeatureGenerator.s"
	@echo "... modules/frameworks/adaBoost.o"
	@echo "... modules/frameworks/adaBoost.i"
	@echo "... modules/frameworks/adaBoost.s"
	@echo "... modules/frameworks/attentionalCascade.o"
	@echo "... modules/frameworks/attentionalCascade.i"
	@echo "... modules/frameworks/attentionalCascade.s"
	@echo "... modules/frameworks/main.o"
	@echo "... modules/frameworks/main.i"
	@echo "... modules/frameworks/main.s"
	@echo "... modules/preprocessing/integralImage.o"
	@echo "... modules/preprocessing/integralImage.i"
	@echo "... modules/preprocessing/integralImage.s"
	@echo "... modules/preprocessing/normalization.o"
	@echo "... modules/preprocessing/normalization.i"
	@echo "... modules/preprocessing/normalization.s"
	@echo "... modules/reporting/timeEval.o"
	@echo "... modules/reporting/timeEval.i"
	@echo "... modules/reporting/timeEval.s"
	@echo "... test/datasetControllerTest.o"
	@echo "... test/datasetControllerTest.i"
	@echo "... test/datasetControllerTest.s"
	@echo "... test/datasetTest.o"
	@echo "... test/datasetTest.i"
	@echo "... test/datasetTest.s"
	@echo "... test/datasetValidatorTest.o"
	@echo "... test/datasetValidatorTest.i"
	@echo "... test/datasetValidatorTest.s"
	@echo "... test/integralImageTest.o"
	@echo "... test/integralImageTest.i"
	@echo "... test/integralImageTest.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/preprocessingTest.o"
	@echo "... test/preprocessingTest.i"
	@echo "... test/preprocessingTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

